make:
	python3 dotsAndBoxes.py http://localhost:4000 12 TheJP16-Alpha1
	#python3 dotsAndBoxes.py http://50774cd16cd5.ngrok.io 420 TheJP16-Alpha
	#python3 dotsAndBoxes.py http://3.12.129.126:5000 2 JoseCifuentes
